@startuml sequence_diagram_usermanagement
title User Management Interaction

actor Employee

participant AdminMenu
participant UserManagement

Employee -> AdminMenu: Login
AdminMenu -> Employee: input("Enter username: ")
AdminMenu -> Employee: input("Enter password: ")

AdminMenu -> AdminMenu: verify_user(username, password)
alt User is Admin
    AdminMenu -> Employee: display_admin_menu()
    Employee -> AdminMenu: Selects "Manage users" from Admin Menu
    AdminMenu -> UserManagement: display_manage_users_menu()
    UserManagement -> UserManagement: print("User Management Menu")
    alt Add New User
        UserManagement -> Employee: input("Enter choice = 1")
        UserManagement -> UserManagement: add_user()
        UserManagement -> Employee: input("Input username: ")
        UserManagement -> Employee: input("Input password: ")
        UserManagement -> Employee: input("Enter role Admin/Member (1/2): ")

        alt if the role is Admin
            UserManagement -> UserManagement: execute INSERT_USER query
        else if the role is Member
            UserManagement -> Employee: input("Input name: ")
            UserManagement -> Employee: input("Input address: ")
            UserManagement -> Employee: input("Input email: ")
            UserManagement -> Employee: input("Input mobile number: ")
            UserManagement -> UserManagement: execute INSERT_USER query
            UserManagement -> UserManagement: execute INSERT_CUSTOMER query
        end
    else Edit User
        UserManagement -> Employee: input("Enter choice = 2")
        UserManagement -> UserManagement: edit_user()
        UserManagement -> UserManagement: execute SHOW_USER query
        UserManagement -> Employee: input("Enter the ID of the user to edit: ")
        UserManagement -> Employee: input("Enter new username: ")
        UserManagement -> Employee: input("Enter new password: ")
        UserManagement -> Employee: input("Enter new role: ")
        UserManagement -> UserManagement: execute UPDATE_USER query
    else Delete User
        UserManagement -> Employee: input("Enter choice = 3")
        UserManagement -> UserManagement: delete_user()
        UserManagement -> UserManagement: execute SHOW_USER query
        UserManagement -> Employee: input("Enter the ID of the user to delete: ")
        UserManagement -> UserManagement: execute DELETE_USER query
    end
    UserManagement -> AdminMenu: return to Admin Menu
    AdminMenu -> Employee: Logout
end

@enduml
