@startuml sequence_diagram_customer
actor Customer
participant "MemberMenu" as MemberMenu
participant "Database" as Database

Customer -> Database: login(username, password)
Database -> Customer: Authentication result (success/failure)

alt Authentication Successful
    MemberMenu -> Customer: display_member_menu()
    MemberMenu -> Customer: Show menu options
    alt See Car List
        Customer -> MemberMenu: Select option 1
        MemberMenu -> Database: execute_query(SHOW_CAR)
        Database -> MemberMenu: Return list of cars
        MemberMenu -> Customer: Display car list
    else Rent Car
        Customer -> MemberMenu: Select option 2
        Customer -> MemberMenu: enter car_id, rental_start_date, rental_end_date
        MemberMenu -> Database: execute_query(GET_CAR_AVAILABILITY)
        Database -> MemberMenu: Return car details (daily_rate, availability)
        MemberMenu -> Database: cursor.execute(NEW_REQUEST)
        Database -> MemberMenu: Return request_id
        MemberMenu -> Database: execute_query(SET_CAR_UNAVAILABLE)
        MemberMenu -> Customer: Display success message with Request ID
    else Return Car
        Customer -> MemberMenu: Select option 3
        MemberMenu -> Database: execute_query(SHOW_RENTED_CAR_BY_USER)
        Database -> MemberMenu: Return rented cars
        MemberMenu -> Customer: Display rented cars
        Customer -> MemberMenu: enter request_id, return_date
        MemberMenu -> Database: execute_query(GET_RENTED_CAR_DETAIL)
        Database -> MemberMenu: Return rental request details
        MemberMenu -> Database: execute_query(COMPLETE_AND_UPDATE_REQUEST)
        MemberMenu -> Database: execute_query(SET_CAR_AVAILABLE)
        MemberMenu -> Customer: Display success message with total cost
    else See Request Status
        Customer -> MemberMenu: Select option 4
        MemberMenu -> Database: execute_query(SHOW_RENTED_CAR_BY_USER)
        Database -> MemberMenu: Return rental requests
        MemberMenu -> Customer: Display rental requests
    end
else Authentication Failed
    Database -> Customer: Show error message
end

@enduml
